# Generated by Django 4.2.4 on 2023-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('cycle_category', models.CharField(choices=[('Expansion', 'Expansion'), ('Peak', 'Peak'), ('Recession', 'Recession'), ('Trough', 'Trough'), ('Recovery', 'Recovery')], max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
