# Generated by Django 4.2.4 on 2023-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('risk', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=100)),
            ],
        ),
    ]
